### ISSUE TITLE
License compatibility

### ISSUE THREAD

**Issue by halo** [x43x61x69/NSStatusItem-Extension#1]
I'm always confused with licenses. Am I right in that I cannot use your library when I plan on using the MIT license for my software? Is there any chance you might change your license to MIT in that case?

Thank you!

**Comment by x43x61x69** [comment]
Hi @halo,

Sorry for the late reply.

You can use it as long as it's code or further modifications are stay GPL. (You just need to release the modified source of this project, not the rest of your project.)

Best,
Cai
